spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://itsdevelopernic22:root@cluster0.jkpkpng.mongodb.net/?retryWrites=true&w=majority
      database: ProductsDB
      port: 27017
      host: hostIpOnWhichMongoIsRunning
server:
  port: 8077
#  information on where to find the Eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
