
server:
  port: 8079  # by setting server port to 0 you allow the services to run on multiple instances on every time of restart (initial port, 8079)
spring:
  application:
    name: inventory-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_inventory_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
