
server:
  port: 8078
spring:
  application:
    name: order-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customer_orders
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#      setting up actuators-> helps in checking the health component of our application
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: never

#      configuring resilience4J properties
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5 #after 5 fail requests the circuit breaker changes status from closed to open
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

